#!/bin/bash

CWD=`pwd`

FILES="*"
SKIP_FILES=( "linkdotfiles" "addotherskipfileshere" )

forceOver=false

while getopts "f" optionName; do
  case "$optionName" in
    f) forceOver=true;;
  esac
done


for file in $FILES; do
  # Test for skip file
  skip=false
  for i in ${SKIP_FILES[@]}; do 
    if [[ $i == ${file} ]] ; then 
      echo "Skip file $file"
      skip=true
      break
    fi 
  done

  # If this file is in skip files, skip it.
  if $skip; then continue; fi

  destFile=$HOME/.$file
  srcFile=$CWD/$file
  # Special Case Handling goes here.
  if [[ $file == "authorized_keys" ]]; then
    # If this is the authorized_keys file, link it into .ssh
    destFile="$HOME/.ssh/authorized_keys"

    # Make sure that the .ssh directory exists
    if [ ! -d $HOME/.ssh ]; then 
      mkdir $HOME/.ssh
      chmod 700 $HOME/.ssh
    fi
  fi

  if [ -e $srcFile ] ; then
    if [ -e $destFile ] || [ -d $destFile ]; then # File exists
      if $forceOver; then
        echo "Deleting $destFile"
        if [ -f $destFile ] || [ -d $destFile ]; then
          rm -rf $destFile
        else
          echo "Unable to delete $destFile"
          continue
        fi
      else
        echo "Not deleting $destFile. To force overwrite, use -f"
        continue
      fi
    fi

    echo "Linking  $srcFile => $destFile"
    if [ -f $srcFile ]; then
      ln $srcFile $destFile
      if [[ $file == "authorized_keys" ]]; then
        chmod 644 $destFile
      fi
    elif [ -d $srcFile ]; then
      ln -s $srcFile $destFile
    else
      echo "Unable to link $srcFile to $destFile"
    fi
  fi
done

