
# == Date ==
# This specifies the date format for the date column. The freeform format
# accepts a strftime like string.
# When "classic" is set, this is set to "date".
# Possible values: date, locale, relative, '+<date_format>'
date: relative

# == Icons ==
icons:
  # When to use icons.
  # Possible values: always, auto, never
  when: never

# == Sorting ==
sorting:
  # Specify what to sort by.
  # Possible values: extension, name, time, size, version
  column: name

  # Whether to group directories together and where.
  # When "classic" is set, this is set to "none".
  # Possible values: first, last, none
  dir-grouping: first

# == Total size ==
# Whether to display the total size of directories.
# Possible values: false, true
total-size: false
